In [1]:
import sys
import os
from dotenv import load_dotenv
load_dotenv()

module_path = os.path.join(os.path.abspath(os.path.join('..')), 'app')
print(module_path)
if module_path not in sys.path:
    sys.path.append(module_path)

import FinanceLib as fl

C:\Projects\FinanceProject\app

In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2
import warnings
warnings.filterwarnings('ignore')

In [3]:
#activate logger
today_dt = fl.date.today().strftime('%Y%m%d')    
log_dir = fl.LOG_DIR + '/logs/' + today_dt

dt_to = fl.date.today()
dt_from = fl.date.today() + fl.timedelta(days=-2)

if not os.path.exists(log_dir):
    os.makedirs(log_dir)
fl.logging.basicConfig(filename=log_dir + '/app.log', filemode='a+', format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', datefmt='%H:%M:%S', level=fl.logging.DEBUG)
logger = fl.logging.getLogger()

In [5]:
# stock_df = fl.get_stock_list_from_db()
# stock_df.head()
# stock_df[stock_df['stock'] == "AAPL"]

In [ ]:
#check what load in work
fl.save_stock_quote_to_db("GOOGL", "america", "2024-08-03", "2025-04-27")
fl.save_stock_quote_to_db("AAPL", "america", "2025-04-26", "2025-04-29")

YF.download() has changed argument auto_adjust default to True

In [10]:
stock_df = fl.get_stock_list_from_db(screener='america')

In [11]:
stock_df.head()

,stock,security,sector,subindustry,exchange,loaddt,is_load,screener,is_avaible_for_trade
0,AKAM,Akamai,Information Technology,Internet Services & Infrastructure,NASDAQ,2023-06-22 22:08:57.954990,1,america,1
1,ALGN,Align Technology,Health Care,Health Care Supplies,NASDAQ,2023-06-22 22:08:57.954990,1,america,1
2,LNT,Alliant Energy,Utilities,Electric Utilities,NASDAQ,2023-06-22 22:08:57.954990,1,america,1
3,GOOGL,Alphabet Inc. (Class A),Communication Services,Interactive Media & Services,NASDAQ,2023-06-22 22:08:57.954990,1,america,1
4,GOOG,Alphabet Inc. (Class C),Communication Services,Interactive Media & Services,NASDAQ,2023-06-22 22:08:57.954990,1,america,1

In [ ]:
fl.get_all_stock_by_period("2024-08-03", "2025-04-27", logger, screener='america', sleep_time=1, is_debug=0)

0 AKAM
YF.download() has changed argument auto_adjust default to True
1 ALGN
2 LNT
3 GOOGL

In [5]:
fl.load_stock_history_to_db("2024-08-03", "2025-04-27", stock_input="GOOGL", check_is_load=1, sleep_time=2, screener_input="america")

GOOGL

In [12]:
fl.daily_update_quote(dt_from="2025-04-28", sleep_time=5, is_debug=1)

AttributeError: 'str' object has no attribute 'strftime'

In [6]:
fl.load_stock_history_to_db("2024-08-03", "2025-04-27", stock_input=None, check_is_load=1, sleep_time=2, screener_input="america")

AKAM
ALGN
LNT
GOOGL
GOOG
AMZN
AMD
AAL
AEP
AMGN
ADI
ANSS
APA
AAPL
AMAT
ACGL
ADSK
AXON
BKR
TECH
BIIB
BKNG
AVGO
CHRW
CDNS
CZR
CDW
CHTR
CINF
CTAS
CSCO
CME
CTSH
CMCSA
CEG
CPRT
CSGP
COST
CSX
XRAY
DXCM
FANG
DLTR
EBAY
EA
ENPH
EQIX
ETSY
EVRG
EXC
EXPE
EXPD
FFIV
FAST
FITB
FSLR
FOXA
GEHC
GEN
GILD
HAS
HSIC
HOLX
HON
HST
HBAN
IDXX
ILMN
INCY
PODD
INTC
INTU
ISRG
JBHT
JKHY
KDP
KLAC
KHC
LRCX
LKQ
MKTX
MAR
MTCH
META
MCHP
MU
MSFT
MRNA
MDLZ
MPWR
MNST
NDAQ
NTAP
NFLX
NWL
NWSA
NWS
NDSN
NTRS
NVDA
NXPI
ORLY
ODFL
ON
PCAR
PANW
PARA
PAYX
PYPL
PEP
POOL
PFG
PTC
QRVO
QCOM
REGN
ROST
SBAC
STX
SWKS
SEDG
SBUX
STLD
SNPS
TMUS
TROW
TTWO
TER
TSLA
TXN
TSCO
TRMB
ULTA
UAL
AMP
ABC
AME
APH
AON
APTV
ANET
AJG
AIZ
T
ATO
AZO
AVB
AVY
BALL
BAC
BBWI
BAX
BDX
COF
CAH
KMX
CCL
CARR
CTLT
CAT
CBOE
CBRE
CE
CNC
CNP
CDAY
CF
CRL
SCHW
CVX
CMG
CB
CHD
CI
C
CFG
CLX
CMS
KO
CL
CMA
CAG
COP
ED
STZ
COO
DOV
DTE
DUK
DD
DXC
EMN
ETN
ECL
EIX
EW
ELV
LLY
EMR
ETR
EOG
EPAM
EQT
EFX
EQR
ESS
EL
RE
ES
EXR
XOM
FDS
FICO
FRT
FDX
GE
GIS
GM
GPC
GPN
GS
HAL
HIG
HCA
PEAK
HSY
HES
HPE
HLT
HD
HRL
HWM
HPQ
HUM
HII
IBM
IEX
ITW
IR
ICE
IFF
IP
IPG
IVZ
INVH
IQV
LIN
LYV
LMT
L
LOW
LYB
MTB
MRO
MPC
MMC
MLM
MAS
MA
MKC
MCD
MCK
MDT
MRK
MET
MTD
MGM
MAA
MHK
MOH
TAP
MCO
MS
MOS
MSI
PXD
PNC
PPG
PPL
PG
PGR
PLD
PRU
PEG
PSA
PHM
PWR
DGX
RL
RJF
RTX
O
LUV
SWK
STT
STE
SYK
SYF
SYY
TPR
TRGP
TGT
TEL
TDY
TFX
TXT
TMO
TJX
TT
TDG
TRV
TFC
TYL
TSN
USB
UDR
UNP
WAT
WEC
WFC
WELL
WST
WRK
WY
WHR
WMB
GWW
XYL
YUM
ZBH
AOS
ABT
ABBV
ACN
ADM
AAP
AES
AFL
A
APD
ALK
ALB
ARE
ALLE
ALL
MO
AMCR
AEE
AXP
AIG
AMT
AWK
WRB
BRK.B
BBY
BIO
BLK
BK
BA
BWA
BXP
BSX
BMY
BR
BRO
BF.B
BG
CPT
CPB
GLW
CTVA
CTRA
CCI
CMI
CVS
DHI
DHR
DRI
DVA
DE
DAL
DVN
DLR
DFS
DIS
DG
D
DPZ
DOW
FE
FIS
FI
FLT
FMC
F
FTNT
FTV
FOX
BEN
FCX
GRMN
IT
OGN
GNRC
GD
GL
IRM
J
JNJ
JCI
JPM
JNPR
K
KEY
KEYS
KMB
KIM
KMI
KR
LHX
LH
LW
LVS
LDOS
LEN
LNC
MSCI
NEM
NEE
NKE
NI
NSC
NOC
NCLH
NRG
NUE
NVR
OXY
OMC
OKE
ORCL
OTIS
PKG
PH
PAYC
PNR
PFE
PCG
PM
PSX
PNW
REG
RF
RSG
RMD
RVTY
RHI
ROK
ROL
ROP
RCL
SPGI
CRM
SLB
SEE
SRE
NOW
SHW
SPG
SJM
SNA
SO
VRSN
VRSK
VRTX
VTRS
WBA
WBD
WDC
WTW
WYNN
XEL
ZBRA
ZION
UPS
URI
UNH
UHS
VLO
VTR
VZ
VFC
VICI
V
VMC
WAB
WMT
WM
ABCL
AMTX
DKNG
PACB

In [8]:
import yfinance as yf
data = yf.download("AAPL", "2025-04-26", "2025-04-29")
df_to_lst = data.reset_index().values.tolist()

In [9]:
df_to_lst

[[Timestamp('2025-04-28 00:00:00'),
  210.13999938964844,
  211.5,
  207.4600067138672,
  210.0,
  38652400]]

In [16]:
fl.get_all_stock_recomendation(logger)

C:\Projects\FinanceProject\FinanceLib.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

SWKS
SEDG
SBUX
STLD
SNPS
TMUS
TROW
TTWO
TER
TSLA
TXN
TSCO
TRMB
CSX
ULTA
UAL
VRSN
VRSK
VRTX
VTRS
WBA
WBD
WTW
WYNN
XEL
ZBRA
ZION
ATVI
ADBE
ADP
AKAM
ALGN
LNT
GOOGL
GOOG
AMZN
AAL
AEP
AMGN
ADI
ANSS
APA
AAPL
AMAT
ACGL
ADSK
AXON
BKR
TECH
BIIB
BKNG
AVGO
CHRW
CDNS
CZR
CDW
CHTR
CINF
CTAS
CSCO
CME
CTSH
CMCSA
CEG
CPRT
AUDCAD
AUDCHF
CSGP
COST
XRAY
DXCM
FANG
DLTR
EBAY
EA
ENPH
EQIX
ETSY
EVRG
NVDA
NXPI
ORLY
ODFL
ON
PCAR
PANW
PARA
PAYX
PYPL
PEP
POOL
PFG
EXPE
EXPD
FFIV
FAST
FITB
FSLR
FTNT
FOXA
FOX
GEHC
GEN
GILD
HAS
HSIC
HOLX
HON
HST
HBAN
IDXX
ILMN
PODD
INTC
INTU
ISRG
JBHT
JKHY
KDP
KLAC
KHC
LRCX
LKQ
MKTX
MAR
MTCH
BRK.B
PRU
TDG
TRV
TFC
TYL
AUDCNH
AMD
TSN
BF.B
USB
UDR
CI
UNP
UPS
URI
UNH
UHS
VLO
VZ
VFC
VICI
V
VMC
WAB
WMT
WM
WAT
WEC
WFC
WELL
WST
ALLE
ALL
MO
AMCR
AEE
AXP
AIG
AMT
AWK
AMP
ABC
AME
APH
AON
APTV
ANET
AJG
AIZ
T
ATO
AZO
BR
BRO
BG
CPT
CPB
COF
CAH
KMX
CCL
CARR
CTLT
CAT
CBOE
CBRE
CE
CNC
CNP
CDAY
CF
CRL
SCHW
CVX
AUDCZK
AUDDKK
CMG
CB
CHD
C
CFG
CLX
CMS
KO
CL
CMA
CAG
COP
ED
STZ
DOV
DOW
DTE
DUK
DD
DXC
EMN
ETN
ECL
EIX
EW
ELV
LLY
EMR
ETR
EOG
EPAM
EQT
EFX
EQR
ESS
EL
RE
NRG
NUE
NVR
OXY
OMC
OKE
ORCL
OGN
OTIS
PKG
FDX
FE
FIS
FI
FLT
FMC
F
FTV
BEN
FCX
GRMN
IT
GNRC
GD
GE
GIS
GM
GPC
GL
GPN
GS
HAL
PTC
QRVO
QCOM
REG
REGN
ROST
SBAC
STX
PEG
PSA
PHM
PWR
DGX
RL
RJF
RTX
O
RF
RSG
RMD
RVTY
RHI
ROK
ROL
ROP
RCL
SPGI
CRM
SLB
SEE
SRE
NOW
SHW
SPG
AUDHKD
AUDHUF
AUDJPY
AUDMXN
AUDNOK
AUDNZD
AUDPLN
AUDSEK
AUDSGD
AUDUSD
AUDZAR
CADCHF
CADCNH
CADCZK
CADDKK
CADHKD
CADHUF
CADJPY
CADMXN
CADNOK
CADPLN
CADSEK
CADSGD
CADZAR
CHFCNH
CHFCZK
CHFDKK
CHFHKD
CHFHUF
CHFJPY
CHFMXN
CHFNOK
CHFPLN
CHFSEK
CHFSGD
CHFTRY
CHFZAR
DKKCZK
DKKHKD
DKKHUF
DKKMXN
DKKNOK
DKKPLN
DKKSEK
DKKSGD
DKKZAR
EURAUD
EURCAD
EURCHF
EURCNH
EURCZK
EURDKK
EURGBP
EURHKD
EURHUF
EURJPY
EURMXN
EURNOK
EURNZD
EURPLN
EURRUB
EURSEK
EURSGD
EURTRY
EURUSD
EURZAR
GBPAUD
GBPCAD
GBPCHF
GBPCNH
GBPCZK
GBPDKK
GBPHKD
GBPHUF
GBPJPY
GBPMXN
GBPNOK
GBPNZD
GBPPLN
GBPSEK
GBPSGD
GBPUSD
GBPZAR
JPYCZK
JPYDKK
JPYHKD
JPYHUF
JPYMXN
JPYNOK
JPYPLN
JPYSEK
JPYSGD
JPYZAR
NOKCZK
NOKHKD
NOKHUF
NOKMXN
NOKPLN
NOKSEK
NOKSGD
NOKZAR
NZDCAD
NZDCHF
NZDCZK
NZDDKK
NZDHKD
NZDHUF
NZDJPY
SJM
SNA
SO
LUV
SWK
STT
STE
SYK
SYF
SYY
TPR
TRGP
TGT
TEL
TDY
TDYError in save data to database: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

CALL finance.p_load_recomendation('TDY', '1d', 'NEUTRAL', 7, 11, 8)
TFX
TXT
TMO
TJX
TT
NZDMXN
NZDNOK
NZDPLN
NZDSEK
NZDSGD
NZDUSD
NZDZAR
USDCAD
USDCHF
USDCNH
USDCZK
USDDKK
USDHKD
USDHUF
USDILS
USDJPY
USDMXN
USDNOK
USDPLN
USDRUB
USDSEK
USDSGD
USDTRY
USDZAR
WDC
WRK
WY
WHR
WMB
GWW
XYL
YUM
ZBH
ZTS
DPZ
MMM
AOS
ABT
ABBV
ACN
ADM
AAP
AES
AFL
A
APD
ALK
ALB
ARE
AVB
AVY
BALL
BAC
BBWI
BAX
BDX
WRB
BBY
BIO
BLK
BK
BA
BWA
BXP
BSX
BMY
COO
GLW
CTVA
CTRA
CCI
CMI
CVS
DHI
DHR
DRI
DVA
DE
DAL
DVN
DLR
DFS
DIS
DG
D
PH
PAYC
PNR
PFE
PCG
PM
PSX
PNW
PXD
PNC
PPG
PPL
PG
PGR
PLD
VTR
EXR
XOM
FDS
FICO
FRT
INCY
HD
HRL
HWM
HPQ
HUM
HII
IBM
IEX
ITW
IR
ICE
IFF
IP
IPG
IVZ
INVH
IQV
EXC
HIG
HCA
PEAK
HSY
HES
HPE
HLT
IRM
J
JNJ
JCI
JPM
JNPR
K
KEY
KEYS
KMB
KIM
KMI
KR
LHX
LH
LW
LVS
LDOS
LEN
LNC
LIN
LYV
LMT
L
LOW
LYB
MTB
MRO
MPC
MMC
MLM
MAS
MA
MKC
ES
MOS
MSI
NEM
NEE
NKE
NI
NSC
NOC
NCLH
META
MCHP
MU
MSFT
MRNA
MDLZ
MPWR
MNST
NDAQ
NTAP
NFLX
NWL
NWSA
NWS
NDSN
NTRS
MCD
MCK
MDT
MRK
MET
MTD
MGM
MAA
MHK
MOH
TAP
MCO
MS
MSCI

{'State': 3, 'CntError': 0, 'lst_error': []}

In [6]:
import pandas_ta

In [24]:
# df = fl.save_stock_quote_to_db("AAPL", 'america', '2020-01-01', '2023-06-29')

In [57]:
df = fl.get_stock_quote_from_db("EURUSD", 'Forex', is_dt_index = 1, is_stock_index = 0, date_from = None, date_to = None)

select * from finance.f_get_quote (NULL, NULL, 'EURUSD', 'Forex')

C:\Projects\FinanceProject\FinanceLib.py:216: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, parse_dates='Dt', index_col = lst_index)

In [53]:
df = fl.get_stock_quote_from_db("AAPL", 'america', is_dt_index = 1, is_stock_index = 0, date_from = None, date_to = None)

select * from finance.f_get_quote (NULL, NULL, 'AAPL', 'america')

C:\Projects\FinanceProject\FinanceLib.py:216: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, parse_dates='Dt', index_col = lst_index)

In [54]:
df.head()

,stock,openvalue,highvalue,lowvalue,closevalue,adjclose,volume
dt,,,,,,,
2018-04-11,AAPL,43.057499,43.480000,42.924999,43.110001,41.040901,89726400.0
2018-04-12,AAPL,43.352501,43.750000,43.259998,43.535000,41.445507,91557200.0
2018-04-13,AAPL,43.695000,43.959999,43.462502,43.682499,41.585926,100497200.0
2018-04-16,AAPL,43.757500,44.047501,43.707500,43.955002,41.845352,86313600.0
2018-04-17,AAPL,44.122501,44.735001,44.102501,44.560001,42.421310,106421600.0

In [56]:
df.ta.log_return(cumulative=True, append=True)

dt
2018-04-11    0.000000
2018-04-12    0.009810
2018-04-13    0.013193
2018-04-16    0.019411
2018-04-17    0.033082
                ...
2023-06-22    1.467354
2023-06-23    1.465641
2023-06-26    1.458059
2023-06-27    1.473006
2023-06-28    1.479314
Name: CUMLOGRET_1, Length: 1381, dtype: float64

In [69]:
df = fl.get_stock_quote_from_db("EURSEK", 'Forex', is_dt_index = 1, is_stock_index = 0, date_from = None, date_to = None)
df.ta.rsi()

select * from finance.f_get_quote (NULL, NULL, 'EURSEK', 'Forex')

C:\Projects\FinanceProject\FinanceLib.py:216: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, parse_dates='Dt', index_col = lst_index)

dt
2023-06-28 00:00:00          NaN
2023-06-28 01:00:00          NaN
2023-06-28 02:00:00          NaN
2023-06-28 03:00:00          NaN
2023-06-28 04:00:00          NaN
2023-06-28 05:00:00          NaN
2023-06-28 06:00:00          NaN
2023-06-28 07:00:00          NaN
2023-06-28 08:00:00          NaN
2023-06-28 09:00:00          NaN
2023-06-28 10:00:00          NaN
2023-06-28 11:00:00          NaN
2023-06-28 12:00:00          NaN
2023-06-28 13:00:00          NaN
2023-06-28 14:00:00    75.407572
2023-06-28 15:00:00    60.737830
2023-06-28 16:00:00    57.907279
2023-06-28 17:00:00    49.185277
2023-06-28 18:00:00    48.571485
2023-06-28 19:00:00    49.902245
2023-06-28 20:00:00    51.113761
2023-06-28 21:00:00    52.722605
2023-06-28 22:00:00    49.072636
2023-06-29 00:00:00    49.066707
2023-06-29 01:00:00    47.804052
2023-06-29 02:00:00    48.714231
2023-06-29 03:00:00    51.242743
2023-06-29 04:00:00    50.926405
2023-06-29 05:00:00    53.689973
2023-06-29 06:00:00    56.990253
2023-06-29 07:00:00    40.605108
2023-06-29 08:00:00    54.634536
2023-06-29 09:00:00    42.701319
2023-06-29 10:00:00    58.236395
2023-06-29 11:00:00    55.354493
2023-06-29 12:00:00    61.458264
2023-06-29 13:00:00    68.018951
2023-06-29 14:00:00    69.199853
Name: RSI_14, dtype: float64

In [4]:
df_pos = fl.get_freedom_open_position()

In [5]:
df_pos.head()

,mkt_id,q,go,Yield,profit_price,profit_close,i,acc_pos_id,curr,instr_id,...,base_contract_code,name,base_currency,name2,scheme_calc,issue_nb,ltr,acd,fv,s
0,30000000001,10,0,0,6.46,-10.00,ABCL.US,108241055,USD,40002580269,...,ABCL.US,AbCellera Biologics,USD,AbCellera Biologics,T2,CA00288U1066,FIX,0,100,74.60
1,30000000001,5,0,0,7.33,-1.14,AMTX.US,108039906,USD,40000092673,...,AMTX.US,Aemetis Inc,USD,Aemetis Inc,T2,US00770K2024,FIX,0,100,37.79
2,30000000001,1,0,0,115.56,-1.73,ATO.US,108252318,USD,40000056728,...,ATO.US,Atmos Energy Corp.,USD,Atmos Energy Corp.,T2,US0495601058,FIX,0,100,117.29
3,30000000001,1,0,0,53.72,0.47,BSX.US,108108131,USD,40000019667,...,BSX.US,Boston Scientific,USD,Boston Scientific,T2,US1011371077,FIX,0,100,53.25
4,30000000001,2,0,0,49.71,4.66,CARR.US,108241061,USD,40000174546,...,CARR.US,Carrier Global Corp,USD,Carrier Global Corp,T2,US14448C1045,FIX,0,100,94.76

In [6]:
df_pos['stock'] = df_pos['i'].apply(lambda x: x.split('.')[0])

In [7]:
df_rec = fl.get_recomendation_from_db()

D:\Projects\FinanceProject\FinanceLib.py:233: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [8]:
df_rec.head()

,stock,security,exchange,screener,rec_1d,rec_1w,rec_1m,buy_count_1d,sell_count_1d,neutral_count_1d,buy_count_1w,sell_count_1w,neutral_count_1w,buy_count_1m,sell_count_1m,neutral_count_1m,closevalue
0,AKAM,Akamai,NASDAQ,america,BUY,BUY,NEUTRAL,15,1,10,12,4,10,8.0,9.0,9.0,89.870003
1,ALGN,Align Technology,NASDAQ,america,BUY,BUY,BUY,14,3,9,12,5,9,12.0,5.0,9.0,353.640015
2,LNT,Alliant Energy,NASDAQ,america,BUY,SELL,NEUTRAL,11,6,9,5,12,9,8.0,9.0,9.0,52.480000
3,GOOGL,Alphabet Inc. (Class A),NASDAQ,america,NEUTRAL,BUY,STRONG_BUY,8,8,10,13,3,10,15.0,1.0,10.0,119.699997
4,GOOG,Alphabet Inc. (Class C),NASDAQ,america,NEUTRAL,BUY,BUY,8,8,10,13,3,10,13.0,2.0,9.0,120.970001

In [8]:
import pandas as pd
df = pd.merge(df_pos, df_rec,  how='left', left_on=['stock'], right_on = ['stock'])

In [9]:
df.head(20)

,mkt_id,q,go,Yield,profit_price,profit_close,i,acc_pos_id,curr,instr_id,...,buy_count_1d,sell_count_1d,neutral_count_1d,buy_count_1w,sell_count_1w,neutral_count_1w,buy_count_1m,sell_count_1m,neutral_count_1m,closevalue
0,30000000001,10,0,0,6.46,-10.00,ABCL.US,108241055,USD,40002580269,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30000000001,5,0,0,7.33,-1.14,AMTX.US,108039906,USD,40000092673,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30000000001,1,0,0,115.56,-1.73,ATO.US,108252318,USD,40000056728,...,17.0,1.0,8.0,17.0,0.0,9.0,15.0,1.0,10.0,116.339996
3,30000000001,1,0,0,53.72,0.47,BSX.US,108108131,USD,40000019667,...,14.0,2.0,10.0,15.0,3.0,8.0,15.0,3.0,8.0,54.090000
4,30000000001,2,0,0,49.71,4.66,CARR.US,108241061,USD,40000174546,...,14.0,3.0,9.0,13.0,2.0,9.0,11.0,0.0,6.0,49.709999
5,30000000001,1,0,0,88.39,2.13,CSGP.US,108241030,USD,40000097804,...,12.0,4.0,10.0,14.0,5.0,7.0,16.0,3.0,7.0,89.000000
6,30000000001,3,0,0,26.66,2.67,DKNG.US,108040239,USD,40000180805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,30000000001,1,0,0,58.99,1.54,FAST.US,108252304,USD,40000019770,...,14.0,4.0,8.0,16.0,4.0,6.0,16.0,1.0,9.0,58.990002
8,30000000001,1,0,0,125.30,3.79,LEN.US,108241132,USD,40000019863,...,14.0,3.0,9.0,14.0,5.0,7.0,16.0,2.0,8.0,125.309998
9,30000000001,1,0,0,188.16,9.43,MMC.US,108108107,USD,40000019893,...,14.0,5.0,7.0,14.0,6.0,6.0,15.0,3.0,8.0,188.080002
10,30000000001,3,0,0,13.23,-2.37,PACB.US,108040291,USD,40000061575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,30000000001,1,0,0,42.82,1.68,ROL.US,108252330,USD,40000076631,...,15.0,4.0,7.0,14.0,3.0,9.0,14.0,4.0,8.0,42.830002

In [20]:
df.columns

Index(['mkt_id', 'q', 'go', 'Yield', 'profit_price', 'profit_close', 'i',
       'acc_pos_id', 'curr', 'instr_id', 'k', 't', 'vm', 'mkt_price',
       'accruedint_a', 'bal_price_a', 'price_a', 'face_val_a', 'close_price',
       'market_value', 'currval', 'open_bal', 'base_contract_code', 'name',
       'base_currency', 'name2', 'scheme_calc', 'issue_nb', 'ltr', 'acd', 'fv',
       's', 'stock', 'security', 'exchange', 'screener', 'rec_1d', 'rec_1w',
       'rec_1m', 'buy_count_1d', 'sell_count_1d', 'neutral_count_1d',
       'buy_count_1w', 'sell_count_1w', 'neutral_count_1w', 'buy_count_1m',
       'sell_count_1m', 'neutral_count_1m', 'closevalue'],
      dtype='object')

In [10]:
df = df.rename(columns={'s': 'balance_value', 'q': 'count', 'price_a': 'in_price'})

In [11]:
columns_show = ['stock', 'name', 'count', 'in_price', 'balance_value', 'mkt_price', 'profit_price', 'profit_close', 'market_value', 'rec_1d', 'rec_1w','rec_1m']

In [12]:
df[columns_show].head(20)

,stock,name,count,in_price,balance_value,mkt_price,profit_price,profit_close,market_value,rec_1d,rec_1w,rec_1m
0,ABCL,AbCellera Biologics,10,7.4600,74.60,6.46,6.46,-10.00,64.60,NaN,NaN,NaN
1,AMTX,Aemetis Inc,5,7.5581,37.79,7.33,7.33,-1.14,36.70,NaN,NaN,NaN
2,ATO,Atmos Energy Corp.,1,117.2900,117.29,115.56,115.56,-1.73,116.34,STRONG_BUY,STRONG_BUY,BUY
3,BSX,Boston Scientific,1,53.2500,53.25,53.72,53.72,0.47,54.06,BUY,BUY,BUY
4,CARR,Carrier Global Corp,2,47.3800,94.76,49.71,49.71,4.66,99.40,BUY,BUY,STRONG_BUY
5,CSGP,CoStar Group Inc,1,86.2600,86.26,88.39,88.39,2.13,89.00,BUY,BUY,BUY
6,DKNG,DraftKings Inc,3,25.7700,77.31,26.62,26.66,2.67,79.68,NaN,NaN,NaN
7,FAST,Fastenal Co,1,57.4500,57.45,58.99,58.99,1.54,58.99,BUY,BUY,STRONG_BUY
8,LEN,Lennar Corp.,1,121.5100,121.51,125.30,125.30,3.79,125.32,BUY,BUY,BUY
9,MMC,Marsh & McLennan,1,178.7300,178.73,188.16,188.16,9.43,188.02,BUY,BUY,BUY
10,PACB,Pacific Biosciences of California Inc,3,14.0200,42.06,13.23,13.23,-2.37,39.87,NaN,NaN,NaN
11,ROL,"Rollins, Inc.",1,41.1400,41.14,42.82,42.82,1.68,42.82,BUY,BUY,BUY

In [35]:
from pandasgui import show

In [20]:
def get_pos_and_rec():
    df_pos = fl.get_freedom_open_position()
    df_pos['stock'] = df_pos['i'].apply(lambda x: x.split('.')[0])
    df_rec = fl.get_recomendation_from_db()
    df = pd.merge(df_pos, df_rec,  how='left', left_on=['stock'], right_on = ['stock'])
    columns_show = ['stock', 'name', 'count', 'in_price', 'balance_value', 'mkt_price', 'profit_price', 'profit_close', 'market_value', 'rec_1d', 'rec_1w','rec_1m']
    return df[columns_show]

In [36]:
gui = show(df)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

In [13]:
# jupyter nbextension enable --py qgrid --sys-prefix
# jupyter nbextension enable --py widgetsnbextension --sys-prefix
# jupyter nbextension install --py bamboolib --sys-prefix
# jupyter nbextension enable --py bamboolib --sys-prefix

SyntaxError: invalid syntax (852628464.py, line 1)

In [18]:
# bam.enable()
bam.disable()

The bamboolib extension was disabled. You can enable it again via 'bam.enable()'. In case that bamboolib was not helpful to you, we are sorry and would like to fix this. Please write us a quick mail to info@8080labs.com so that we can serve you better in the future. Best regards, Tobias and Florian

In [17]:
import bamboolib as bam
import pandas as pd
result = df[columns_show]
bam.show(result)

VBox(children=(HTML(value='<div class="bamboolib-notification bamboolib-notification-info"><b>Pro Tip:</b> sav…

In [22]:
df = fl.get_pos_and_rec()

In [23]:
df.head(20)

,stock,name,count,in_price,balance_value,mkt_price,profit_price,profit_close,market_value,rec_1d,rec_1w,rec_1m
0,ABCL,AbCellera Biologics,10,7.4600,74.60,6.46,6.46,-10.00,64.60,NaN,NaN,NaN
1,AMTX,Aemetis Inc,5,7.5581,37.79,7.33,7.33,-1.14,36.70,NaN,NaN,NaN
2,ATO,Atmos Energy Corp.,1,117.2900,117.29,115.56,115.56,-1.73,116.34,STRONG_BUY,STRONG_BUY,BUY
3,BSX,Boston Scientific,1,53.2500,53.25,53.72,53.72,0.47,54.06,BUY,BUY,BUY
4,CARR,Carrier Global Corp,2,47.3800,94.76,49.71,49.71,4.66,99.40,BUY,BUY,STRONG_BUY
5,CSGP,CoStar Group Inc,1,86.2600,86.26,88.39,88.39,2.13,89.00,BUY,BUY,BUY
6,DKNG,DraftKings Inc,3,25.7700,77.31,26.62,26.66,2.67,79.68,NaN,NaN,NaN
7,FAST,Fastenal Co,1,57.4500,57.45,58.99,58.99,1.54,58.99,BUY,BUY,STRONG_BUY
8,LEN,Lennar Corp.,1,121.5100,121.51,125.30,125.30,3.79,125.32,BUY,BUY,BUY
9,MMC,Marsh & McLennan,1,178.7300,178.73,188.16,188.16,9.43,188.02,BUY,BUY,BUY
10,PACB,Pacific Biosciences of California Inc,3,14.0200,42.06,13.23,13.23,-2.37,39.87,NaN,NaN,NaN
11,ROL,"Rollins, Inc.",1,41.1400,41.14,42.82,42.82,1.68,42.82,BUY,BUY,BUY

In [121]:
df = fl.get_stock_quote_from_db("AAPL", "america", "2023-01-01", "2023-07-06")

select * from finance.f_get_quote (NULL, NULL, 'AAPL', 'america')

C:\Projects\FinanceProject\FinanceLib.py:225: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  soup = bs.BeautifulSoup(resp.text, 'lxml')

In [102]:
df.head()

,dt,stock,openvalue,highvalue,lowvalue,closevalue,adjclose,volume
0,2018-01-02,AAPL,42.540001,43.075001,42.314999,43.064999,40.831596,NaN
1,2018-01-03,AAPL,43.132500,43.637501,42.990002,43.057499,40.824471,NaN
2,2018-01-04,AAPL,43.134998,43.367500,43.020000,43.257500,41.014107,NaN
3,2018-01-05,AAPL,43.360001,43.842499,43.262501,43.750000,41.481071,NaN
4,2018-01-08,AAPL,43.587502,43.902500,43.482498,43.587502,41.326992,NaN

In [103]:
df.size

11080

In [104]:
df.index

RangeIndex(start=0, stop=1385, step=1)

In [105]:
df['Change'] = df.groupby('stock').adjclose.pct_change()*100
df['Change7'] = df.groupby('stock').adjclose.pct_change(7)*100
df['Change30'] = df.groupby('stock').adjclose.pct_change(30)*100
df['Change90'] = df.groupby('stock').adjclose.pct_change(90)*100
df['Change180'] = df.groupby('stock').adjclose.pct_change(180)*100
df['Change360'] = df.groupby('stock').adjclose.pct_change(360)*100
df['Change'] = df['Change'].round(2)
df['Change7'] = df['Change7'].round(2)
df['Change30'] = df['Change30'].round(2)
df['Change90'] = df['Change90'].round(2)
df['Change180'] = df['Change180'].round(2)
df['Change360'] = df['Change360'].round(2)

In [128]:
df[df['dt'] == '2023-07-05'].head()

,dt,stock,openvalue,highvalue,lowvalue,closevalue,adjclose,volume,change,change7,change30,change90,change180,change360
1384,2023-07-05,AAPL,191.570007,192.979996,190.619995,191.330002,191.330002,46860000.0,-0.01,0.02,0.09,0.28,0.34,0.21

In [109]:
import pandas_ta as ta

In [118]:
# help(ta.bbands)

In [117]:
# df[df['dt'] == '2023-07-05'].ta.bbands.head()
df['rsi'] = df.ta.rsi()

In [119]:
df[df['dt'] == '2023-07-05']

,dt,stock,openvalue,highvalue,lowvalue,closevalue,adjclose,volume,Change,Change7,Change30,Change90,Change180,Change360,rsi
1384,2023-07-05,AAPL,191.570007,192.979996,190.619995,191.330002,191.330002,46860000.0,-0.59,2.49,9.23,28.24,34.42,20.86,68.350259

In [120]:
df.ta.bbands()

       BBL_5_2.0   BBM_5_2.0   BBU_5_2.0  BBB_5_2.0  BBP_5_2.0
0            NaN         NaN         NaN        NaN        NaN
1            NaN         NaN         NaN        NaN        NaN
2            NaN         NaN         NaN        NaN        NaN
3            NaN         NaN         NaN        NaN        NaN
4      42.783833   43.343500   43.903167   2.582475   0.717988
...          ...         ...         ...        ...        ...
1380  184.574109  187.251999  189.929889   2.860199   0.873055
1381  184.541998  187.769998  190.997998   3.438249   0.781908
1382  183.596086  189.228000  194.859913   5.952516   0.920994
1383  186.276106  190.666000  195.055895   4.604801   0.704334
1384  187.787293  191.320001  194.852710   3.692984   0.501415

[1385 rows x 5 columns]

In [126]:
df = fl.get_pct_change(df)

In [137]:
df.head()

,stock,openvalue,highvalue,lowvalue,closevalue,adjclose,volume,change,change7,change30,change90,change180,change360,rsi
dt,,,,,,,,,,,,,,
2022-07-07,AKAM,92.150002,93.029999,91.800003,92.900002,92.900002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-07-08,AKAM,92.570000,92.610001,91.089996,92.150002,92.150002,NaN,-0.01,NaN,NaN,NaN,NaN,NaN,NaN
2022-07-11,AKAM,91.410004,91.930000,90.230003,90.580002,90.580002,NaN,-0.02,NaN,NaN,NaN,NaN,NaN,NaN
2022-07-12,AKAM,90.690002,91.309998,88.989998,89.330002,89.330002,NaN,-0.01,NaN,NaN,NaN,NaN,NaN,NaN
2022-07-13,AKAM,87.809998,88.699997,87.660004,88.160004,88.160004,NaN,-0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
df.columns

Index(['dt', 'stock', 'openvalue', 'highvalue', 'lowvalue', 'closevalue',
       'adjclose', 'volume'],
      dtype='object')

In [195]:
from datetime import datetime, timedelta
dt_from = datetime.today() - timedelta(days = 365)
dt_to = datetime.today() - timedelta(days = 1)
print(dt_from.strftime("%Y-%m-%d"), dt_to.strftime("%Y-%m-%d"))

2022-07-06 2023-07-05

In [197]:
from datetime import datetime, timedelta
dt_from = datetime.today() - timedelta(days = 365)
dt_to = datetime.today() - timedelta(days = 1)
print(dt_from.strftime("%Y-%m-%d"), dt_to.strftime("%Y-%m-%d"))
df = fl.get_stock_quote_from_db(None, "america", dt_from.strftime("%Y-%m-%d"), dt_to.strftime("%Y-%m-%d"), is_dt_index=0, is_stock_index=0)
df = fl.get_pct_change(df)
df['rsi'] = df.ta.rsi()
df_actual = df[df['dt'] == dt_to]
df_result = pd.merge(df_pos, df_actual,  how='left', left_on=['stock'], right_on=['stock'])

2022-07-06 2023-07-05
select * from finance.f_get_quote ('2022-07-06', '2023-07-05', NULL, 'america')

In [198]:
df_result.head()

,stock,name,count,in_price,balance_value,mkt_price,profit_price,profit_close,market_value,rec_1d,...,closevalue,adjclose,volume,change,change7,change30,change90,change180,change360,rsi
0,ABCL,AbCellera Biologics,10,7.4600,74.60,6.52,6.52,-9.40,65.30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AMTX,Aemetis Inc,5,7.5581,37.79,7.05,7.05,-2.54,35.30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ATO,Atmos Energy Corp.,1,117.2900,117.29,118.60,118.60,1.31,118.49,BUY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BSX,Boston Scientific,1,53.2500,53.25,53.31,53.31,0.06,53.23,SELL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CARR,Carrier Global Corp,2,47.3800,94.76,49.24,49.24,3.72,98.46,BUY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
df.size

1001096

In [182]:
df = fl.get_pct_change(df)

In [183]:
df['rsi'] = df.ta.rsi()

In [148]:
df.index

RangeIndex(start=0, stop=125137, step=1)

In [184]:
df_actual = df[df['dt'] == '2023-07-05']

In [185]:
df_actual.head()

,dt,stock,openvalue,highvalue,lowvalue,closevalue,adjclose,volume,change,change7,change30,change90,change180,change360,rsi
125636,2023-07-05,AKAM,90.599998,90.839996,90.059998,90.220001,90.220001,1217300.0,-0.01,0.02,0.03,0.20,0.12,NaN,12.197161
125638,2023-07-05,ALGN,339.730011,339.730011,327.190002,336.820007,336.820007,789900.0,-0.02,0.02,0.16,0.10,0.59,NaN,75.883180
125640,2023-07-05,LNT,52.970001,53.930000,52.740002,53.580002,53.580002,1492800.0,0.01,0.03,0.02,0.02,0.11,NaN,39.117822
125642,2023-07-05,GOOGL,119.239998,122.610001,119.230003,121.750000,121.750000,27556500.0,0.02,-0.00,-0.01,0.34,0.23,NaN,46.376510
125644,2023-07-05,GOOG,120.059998,123.370003,120.059998,122.629997,122.629997,17815700.0,0.02,-0.00,-0.01,0.35,0.23,NaN,46.505869

In [186]:
df_pos =fl.get_pos_and_rec()

C:\Projects\FinanceProject\FinanceLib.py:238: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [187]:
df_pos.head()

,stock,name,count,in_price,balance_value,mkt_price,profit_price,profit_close,market_value,rec_1d,rec_1w,rec_1m
0,ABCL,AbCellera Biologics,10,7.4600,74.60,6.52,6.52,-9.40,65.30,NaN,NaN,NaN
1,AMTX,Aemetis Inc,5,7.5581,37.79,7.05,7.05,-2.54,35.30,NaN,NaN,NaN
2,ATO,Atmos Energy Corp.,1,117.2900,117.29,118.60,118.60,1.31,118.49,BUY,STRONG_BUY,BUY
3,BSX,Boston Scientific,1,53.2500,53.25,53.31,53.31,0.06,53.23,SELL,BUY,BUY
4,CARR,Carrier Global Corp,2,47.3800,94.76,49.24,49.24,3.72,98.46,BUY,BUY,STRONG_BUY

In [188]:
df_result = pd.merge(df_pos, df_actual,  how='left', left_on=['stock'], right_on=['stock'])

In [189]:
df_result.head(15)

,stock,name,count,in_price,balance_value,mkt_price,profit_price,profit_close,market_value,rec_1d,...,closevalue,adjclose,volume,change,change7,change30,change90,change180,change360,rsi
0,ABCL,AbCellera Biologics,10,7.4600,74.60,6.52,6.52,-9.40,65.30,NaN,...,6.520000,6.520000,NaN,-0.01,-0.11,0.12,-0.23,-0.39,NaN,42.013299
1,AMTX,Aemetis Inc,5,7.5581,37.79,7.05,7.05,-2.54,35.30,NaN,...,7.050000,7.050000,NaN,-0.03,0.26,1.19,0.81,0.13,NaN,63.030886
2,ATO,Atmos Energy Corp.,1,117.2900,117.29,118.60,118.60,1.31,118.49,BUY,...,118.589996,118.589996,794000.0,0.01,0.04,0.02,0.03,0.19,NaN,47.917951
3,BSX,Boston Scientific,1,53.2500,53.25,53.31,53.31,0.06,53.23,SELL,...,53.250000,53.250000,9640300.0,-0.01,-0.01,-0.01,0.13,0.32,NaN,45.060959
4,CARR,Carrier Global Corp,2,47.3800,94.76,49.24,49.24,3.72,98.46,BUY,...,49.240002,49.240002,2612200.0,-0.02,0.02,0.16,0.12,0.44,NaN,45.635863
5,CSGP,CoStar Group Inc,1,86.2600,86.26,87.92,87.92,1.66,88.59,NEUTRAL,...,88.620003,88.620003,3546100.0,0.01,0.02,0.13,0.25,0.24,NaN,46.197140
6,DKNG,DraftKings Inc,3,25.7700,77.31,26.09,26.09,0.96,78.21,NaN,...,26.080000,26.080000,NaN,-0.01,0.04,0.08,0.37,0.97,NaN,58.441791
7,FAST,Fastenal Co,1,57.4500,57.45,57.97,57.97,0.52,58.26,BUY,...,58.250000,58.250000,2868200.0,-0.00,0.02,0.06,0.14,0.27,NaN,44.995013
8,LEN,Lennar Corp.,1,121.5100,121.51,124.63,124.63,3.12,124.22,NEUTRAL,...,124.290001,124.290001,1966600.0,-0.01,0.02,0.09,0.28,0.64,NaN,52.491150
9,MMC,Marsh & McLennan,1,178.7300,178.73,186.01,186.01,7.28,186.01,BUY,...,186.029999,186.029999,1363900.0,0.00,0.01,0.03,0.14,0.20,NaN,52.483302
10,PACB,Pacific Biosciences of California Inc,3,14.0200,42.06,12.81,12.81,-3.63,38.55,NaN,...,12.850000,12.850000,NaN,-0.00,0.03,0.01,0.38,0.96,NaN,49.807363
11,ROL,"Rollins, Inc.",1,41.1400,41.14,43.02,43.02,1.88,43.01,BUY,...,43.020000,43.020000,1558000.0,0.02,0.04,0.05,0.22,0.20,NaN,45.132958

In [180]:
fl.load_stock_history_to_db("2018-01-01", "2023-07-06", stock_input="DKNG")

C:\Projects\FinanceProject\FinanceLib.py:290: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

DKNG
[*********************100%***********************]  1 of 1 completed
execute_values() done

In [174]:
df[df["stock"] == "ABCL"]

Empty DataFrame
Columns: [dt, stock, openvalue, highvalue, lowvalue, closevalue, adjclose, volume]
Index: []

In [190]:
df_actual.head(100)

,dt,stock,openvalue,highvalue,lowvalue,closevalue,adjclose,volume,change,change7,change30,change90,change180,change360,rsi
125636,2023-07-05,AKAM,90.599998,90.839996,90.059998,90.220001,90.220001,1217300.0,-0.01,0.02,0.03,0.20,0.12,NaN,12.197161
125638,2023-07-05,ALGN,339.730011,339.730011,327.190002,336.820007,336.820007,789900.0,-0.02,0.02,0.16,0.10,0.59,NaN,75.883180
125640,2023-07-05,LNT,52.970001,53.930000,52.740002,53.580002,53.580002,1492800.0,0.01,0.03,0.02,0.02,0.11,NaN,39.117822
125642,2023-07-05,GOOGL,119.239998,122.610001,119.230003,121.750000,121.750000,27556500.0,0.02,-0.00,-0.01,0.34,0.23,NaN,46.376510
125644,2023-07-05,GOOG,120.059998,123.370003,120.059998,122.629997,122.629997,17815700.0,0.02,-0.00,-0.01,0.35,0.23,NaN,46.505869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125826,2023-07-05,NWSA,19.400000,19.530001,19.200001,19.500000,19.500000,2286700.0,-0.00,0.04,0.05,0.12,0.23,NaN,45.195623
125828,2023-07-05,NWS,19.610001,19.740000,19.410000,19.709999,19.709999,512200.0,-0.00,0.04,0.05,0.12,0.22,NaN,45.204064
125830,2023-07-05,NDSN,245.580002,245.580002,242.220001,242.440002,242.440002,164400.0,-0.02,0.03,0.12,0.09,0.14,NaN,53.667481
125832,2023-07-05,NTRS,74.709999,75.459999,74.070000,74.199997,74.199997,1108200.0,-0.02,0.04,0.04,-0.19,-0.13,NaN,47.281239
125834,2023-07-05,NVDA,421.350006,431.769989,420.850006,423.170013,423.170013,32292800.0,-0.00,0.00,0.35,0.79,2.54,NaN,58.995329

In [259]:
df = fl.get_pos_and_rec()

C:\Projects\FinanceProject\FinanceLib.py:238: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

america 2022-07-06 2023-07-05
select * from finance.f_get_quote ('2022-07-06', '2023-07-05', NULL, 'america')

C:\Projects\FinanceProject\FinanceLib.py:225: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, parse_dates='Dt')

In [260]:
df.head(15)

,stock,name,count,in_price,balance_value,mkt_price,profit_price,profit_close,market_value,rec_1d,rec_1w,rec_1m,rec_loaddt,change7,change30,change90,change180,change360,rsi
0,ABCL,AbCellera Biologics,10,7.4600,74.60,6.52,6.52,-9.40,65.30,NaN,NaN,NaN,NaT,-0.11,0.12,-0.23,-0.39,NaN,42.013299
1,AMTX,Aemetis Inc,5,7.5581,37.79,7.05,7.05,-2.54,35.30,NaN,NaN,NaN,NaT,0.26,1.19,0.81,0.13,NaN,63.030886
2,ATO,Atmos Energy Corp.,1,117.2900,117.29,118.60,118.60,1.31,118.49,BUY,STRONG_BUY,BUY,2023-07-06 13:55:55.430160,0.04,0.02,0.03,0.19,NaN,47.917951
3,BSX,Boston Scientific,1,53.2500,53.25,53.31,53.31,0.06,53.23,SELL,BUY,BUY,2023-07-06 14:08:56.337976,-0.01,-0.01,0.13,0.32,NaN,45.060959
4,CARR,Carrier Global Corp,2,47.3800,94.76,49.24,49.24,3.72,98.46,BUY,BUY,STRONG_BUY,2023-07-06 13:56:32.902057,0.02,0.16,0.12,0.44,NaN,45.635863
5,CSGP,CoStar Group Inc,1,86.2600,86.26,87.92,87.92,1.66,88.59,NEUTRAL,BUY,BUY,2023-07-06 13:50:49.509759,0.02,0.13,0.25,0.24,NaN,46.197140
6,DKNG,DraftKings Inc,3,25.7700,77.31,26.09,26.09,0.96,78.21,NaN,NaN,NaN,NaT,0.04,0.08,0.37,0.97,NaN,58.441791
7,FAST,Fastenal Co,1,57.4500,57.45,57.97,57.97,0.52,58.26,BUY,BUY,BUY,2023-07-06 13:51:37.585354,0.02,0.06,0.14,0.27,NaN,44.995013
8,LEN,Lennar Corp.,1,121.5100,121.51,124.63,124.63,3.12,124.22,NEUTRAL,BUY,BUY,2023-07-06 14:11:54.425523,0.02,0.09,0.28,0.64,NaN,52.491150
9,MMC,Marsh & McLennan,1,178.7300,178.73,186.01,186.01,7.28,186.01,BUY,BUY,BUY,2023-07-06 14:01:12.531675,0.01,0.03,0.14,0.20,NaN,52.483302
10,PACB,Pacific Biosciences of California Inc,3,14.0200,42.06,12.81,12.81,-3.63,38.55,NaN,NaN,NaN,NaT,0.03,0.01,0.38,0.96,NaN,49.807361
11,ROL,"Rollins, Inc.",1,41.1400,41.14,43.02,43.02,1.88,43.01,BUY,BUY,BUY,2023-07-06 14:13:34.252500,0.04,0.05,0.22,0.20,NaN,45.132958

In [ ]:
df_pos = fl.get_freedom_open_position()
df_pos['stock'] = df_pos['i'].apply(lambda x: x.split('.')[0])
df_rec = get_recomendation_from_db()
df = pd.merge(df_pos, df_rec,  how='left', left_on=['stock'], right_on=['stock'])
df = df.rename(columns={'s': 'balance_value', 'q': 'count', 'price_a': 'in_price'})
df_actual = get_df_actual_price_and_metrics("america")
df_result = pd.merge(df_pos, df_actual, how='left', left_on=['stock'], right_on=['stock'])

In [229]:
df_pos = fl.get_freedom_open_position()

In [230]:
df_pos['stock'] = df_pos['i'].apply(lambda x: x.split('.')[0])

In [231]:
df_pos.head()

,mkt_id,q,go,Yield,profit_price,profit_close,i,acc_pos_id,curr,instr_id,...,name,base_currency,name2,scheme_calc,issue_nb,ltr,acd,fv,s,stock
0,30000000001,10,0,0,6.52,-9.40,ABCL.US,108241055,USD,40002580269,...,AbCellera Biologics,USD,AbCellera Biologics,T2,CA00288U1066,FIX,0,100,74.60,ABCL
1,30000000001,5,0,0,7.05,-2.54,AMTX.US,108039906,USD,40000092673,...,Aemetis Inc,USD,Aemetis Inc,T2,US00770K2024,FIX,0,100,37.79,AMTX
2,30000000001,1,0,0,118.60,1.31,ATO.US,108252318,USD,40000056728,...,Atmos Energy Corp.,USD,Atmos Energy Corp.,T2,US0495601058,FIX,0,100,117.29,ATO
3,30000000001,1,0,0,53.31,0.06,BSX.US,108108131,USD,40000019667,...,Boston Scientific,USD,Boston Scientific,T2,US1011371077,FIX,0,100,53.25,BSX
4,30000000001,2,0,0,49.24,3.72,CARR.US,108241061,USD,40000174546,...,Carrier Global Corp,USD,Carrier Global Corp,T2,US14448C1045,FIX,0,100,94.76,CARR

In [232]:
df_rec = fl.get_recomendation_from_db()

C:\Projects\FinanceProject\FinanceLib.py:238: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [233]:
df_rec.head()

,stock,security,exchange,screener,rec_1d,rec_1w,rec_1m,buy_count_1d,sell_count_1d,neutral_count_1d,buy_count_1w,sell_count_1w,neutral_count_1w,buy_count_1m,sell_count_1m,neutral_count_1m,closevalue
0,AKAM,Akamai,NASDAQ,america,SELL,NEUTRAL,NEUTRAL,7,10,9,10,6,10,7.0,10.0,9.0,90.220001
1,ALGN,Align Technology,NASDAQ,america,NEUTRAL,BUY,BUY,12,5,9,11,5,10,10.0,8.0,8.0,336.820007
2,LNT,Alliant Energy,NASDAQ,america,NEUTRAL,SELL,NEUTRAL,9,9,8,5,11,10,8.0,9.0,9.0,53.580002
3,GOOGL,Alphabet Inc. (Class A),NASDAQ,america,NEUTRAL,BUY,STRONG_BUY,8,9,9,13,3,10,15.0,1.0,10.0,121.750000
4,GOOG,Alphabet Inc. (Class C),NASDAQ,america,NEUTRAL,BUY,BUY,8,9,9,13,3,10,13.0,2.0,9.0,122.629997

In [234]:
df = pd.merge(df_pos, df_rec,  how='left', left_on=['stock'], right_on=['stock'])

In [235]:
df = df.rename(columns={'s': 'balance_value', 'q': 'count', 'price_a': 'in_price'})

In [236]:
df.head()

,mkt_id,count,go,Yield,profit_price,profit_close,i,acc_pos_id,curr,instr_id,...,buy_count_1d,sell_count_1d,neutral_count_1d,buy_count_1w,sell_count_1w,neutral_count_1w,buy_count_1m,sell_count_1m,neutral_count_1m,closevalue
0,30000000001,10,0,0,6.52,-9.40,ABCL.US,108241055,USD,40002580269,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30000000001,5,0,0,7.05,-2.54,AMTX.US,108039906,USD,40000092673,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30000000001,1,0,0,118.60,1.31,ATO.US,108252318,USD,40000056728,...,14.0,2.0,10.0,17.0,0.0,9.0,15.0,1.0,10.0,118.589996
3,30000000001,1,0,0,53.31,0.06,BSX.US,108108131,USD,40000019667,...,8.0,9.0,9.0,14.0,4.0,8.0,15.0,3.0,8.0,53.250000
4,30000000001,2,0,0,49.24,3.72,CARR.US,108241061,USD,40000174546,...,13.0,3.0,10.0,13.0,4.0,7.0,11.0,1.0,5.0,49.240002

In [239]:
df_actual = fl.get_df_actual_price_and_metrics("america")

america 2022-07-06 2023-07-05
select * from finance.f_get_quote ('2022-07-06', '2023-07-05', NULL, 'america')

C:\Projects\FinanceProject\FinanceLib.py:225: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, parse_dates='Dt')

In [254]:
screener = "america"
dt_from = datetime.today() - timedelta(days=365)
dt_to = datetime.today() - timedelta(days=1)
print(screener, dt_from.strftime("%Y-%m-%d"), dt_to.strftime("%Y-%m-%d"))
df_actual_price = fl.get_stock_quote_from_db(None, screener, dt_from.strftime("%Y-%m-%d"), dt_to.strftime("%Y-%m-%d"), is_dt_index=0, is_stock_index=0)

america 2022-07-06 2023-07-05
select * from finance.f_get_quote ('2022-07-06', '2023-07-05', NULL, 'america')

C:\Projects\FinanceProject\FinanceLib.py:225: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, parse_dates='Dt')

In [255]:
df_actual_price = fl.get_pct_change(df_actual_price)
df_actual_price['rsi'] = df_actual_price.ta.rsi()
df_actual_price = df_actual_price[df_actual_price['dt'] == dt_to.strftime("%Y-%m-%d")]

In [256]:
df_actual_price.head()

,dt,stock,openvalue,highvalue,lowvalue,closevalue,adjclose,volume,change,change7,change30,change90,change180,change360,rsi
124636,2023-07-05,AKAM,90.599998,90.839996,90.059998,90.220001,90.220001,1217300.0,-0.01,0.02,0.03,0.20,0.12,NaN,12.197161
124638,2023-07-05,ALGN,339.730011,339.730011,327.190002,336.820007,336.820007,789900.0,-0.02,0.02,0.16,0.10,0.59,NaN,75.883180
124640,2023-07-05,LNT,52.970001,53.930000,52.740002,53.580002,53.580002,1492800.0,0.01,0.03,0.02,0.02,0.11,NaN,39.117822
124642,2023-07-05,GOOGL,119.239998,122.610001,119.230003,121.750000,121.750000,27556500.0,0.02,-0.00,-0.01,0.34,0.23,NaN,46.376510
124644,2023-07-05,GOOG,120.059998,123.370003,120.059998,122.629997,122.629997,17815700.0,0.02,-0.00,-0.01,0.35,0.23,NaN,46.505869

In [240]:
df_actual.head()

Empty DataFrame
Columns: [dt, stock, openvalue, highvalue, lowvalue, closevalue, adjclose, volume, change, change7, change30, change90, change180, change360, rsi]
Index: []

In [222]:
df_result = pd.merge(df, df_actual, how='left', left_on=['stock'], right_on=['stock'])

In [223]:
df_result.columns

Index(['mkt_id', 'count', 'go', 'Yield', 'profit_price', 'profit_close', 'i',
       'acc_pos_id', 'curr', 'instr_id', 'k', 't', 'vm', 'mkt_price',
       'accruedint_a', 'bal_price_a', 'in_price', 'face_val_a', 'close_price',
       'market_value', 'currval', 'open_bal', 'base_contract_code', 'name',
       'base_currency', 'name2', 'scheme_calc', 'issue_nb', 'ltr', 'acd', 'fv',
       'balance_value', 'stock', 'security', 'exchange', 'screener', 'rec_1d',
       'rec_1w', 'rec_1m', 'buy_count_1d', 'sell_count_1d', 'neutral_count_1d',
       'buy_count_1w', 'sell_count_1w', 'neutral_count_1w', 'buy_count_1m',
       'sell_count_1m', 'neutral_count_1m', 'closevalue_x', 'dt', 'openvalue',
       'highvalue', 'lowvalue', 'closevalue_y', 'adjclose', 'volume', 'change',
       'change7', 'change30', 'change90', 'change180', 'change360', 'rsi'],
      dtype='object')

In [224]:
columns_show = ['stock',
                    'name',
                    'count',
                    'in_price',
                    'balance_value',
                    'mkt_price',
                    'profit_price',
                    'profit_close',
                    'market_value',
                    'rec_1d',
                    'rec_1w',
                    'rec_1m',
                    'change7',
                    'change30',
                    'change90',
                    'change180',
                    'change360',
                    'rsi'
                    ]

In [225]:
df_result.head()

,mkt_id,count,go,Yield,profit_price,profit_close,i,acc_pos_id,curr,instr_id,...,closevalue_y,adjclose,volume,change,change7,change30,change90,change180,change360,rsi
0,30000000001,10,0,0,6.52,-9.40,ABCL.US,108241055,USD,40002580269,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30000000001,5,0,0,7.05,-2.54,AMTX.US,108039906,USD,40000092673,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30000000001,1,0,0,118.60,1.31,ATO.US,108252318,USD,40000056728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,30000000001,1,0,0,53.31,0.06,BSX.US,108108131,USD,40000019667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30000000001,2,0,0,49.24,3.72,CARR.US,108241061,USD,40000174546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN